// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WegGridCore.EF;

#nullable disable

namespace WegGridCore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240308205428_AddGridTablesToDB_2")]
    partial class AddGridTablesToDB_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("WegGridCore.Models.ColorFenceModel", b =>
                {
                    b.Property<int>("ColorFenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ColorFenceId");

                    b.ToTable("ColorFence");
                });

            modelBuilder.Entity("WegGridCore.Models.HeightFenceModel", b =>
                {
                    b.Property<int>("HeightFenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HeightFenceId");

                    b.ToTable("HeightFence");
                });

            modelBuilder.Entity("WegGridCore.Models.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorFenceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DifferenceFenceGrid")
                        .HasColumnType("REAL");

                    b.Property<int>("HeightFenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalLongFence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL");

                    b.Property<double>("TotalLongGrid")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ColorFenceId");

                    b.HasIndex("HeightFenceId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("WegGridCore.Models.OrderModel", b =>
                {
                    b.HasOne("WegGridCore.Models.ColorFenceModel", "ColorFence")
                        .WithMany("OrderModel")
                        .HasForeignKey("ColorFenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WegGridCore.Models.HeightFenceModel", "HeightFence")
                        .WithMany("OrderModel")
                        .HasForeignKey("HeightFenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColorFence");

                    b.Navigation("HeightFence");
                });

            modelBuilder.Entity("WegGridCore.Models.ColorFenceModel", b =>
                {
                    b.Navigation("OrderModel");
                });

            modelBuilder.Entity("WegGridCore.Models.HeightFenceModel", b =>
                {
                    b.Navigation("OrderModel");
                });
#pragma warning restore 612, 618
        }
    }
}
